title: IT Teacher PL
email: marcin.wojciechowski@goleniow.edu.pl
description: >- 
  Materiały edukacyjne dla uczniów technikum w zawodzie technik programista.
baseurl: "" # jeśli używasz GitHub Pages w formacie nazwa_uzytkownika.github.io zostaw puste
url: "https://wojcieh.github.io" # adres strony
theme: minima # możesz zmienić na inny motyw

header_pages:
  - index.md
  - materialy.md
  - projekty.md

